global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'restful-web-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']  # Use localhost:8081 if not on Docker Desktop